# SUB CONSULTAS

/*

- SON CONSULTAS QUE SE EJECUTAN DENTRO DE OTRAS
- CONSISTE EN UTILIZAR LOS RESULTADOS DE LA SUBCONSULTA PARA OPERAR EN LA CONSULTA PRINCIPAL
- JUGANDO CON LAS CLAVES AJENAS / FORANEAS

*/

# SACAR USUARIOS CON ENTRADAS
SELECT * FROM usuarios WHERE id IN (SELECT usuario_id FROM entradas);

# SACER LOS USUARIOS QUE TENGAN ALGUNA ENTRADA QUE EN SU TITULO HABLE DE RESIDENT EVIL
SELECT nombre, apellidos FROM usuarios WHERE id
IN (SELECT usuario_id FROM entradas WHERE titulo LIKE "%resident%");

# SACAR TODAS LAS ENTRADAS DE LA CATEGORIA ACCION UTILIZANDO SU NOMBRE
SELECT titulo FROM entradas WHERE categoria_id IN (SELECT id FROM categorias where nombre = 'Terror');

# MOSTRAR LAS CATEGORIAS CON TRES O MAS ENTRADAS
SELECT nombre FROM categorias WHERE 
id IN (SELECT categoria_id FROM entradas GROUP BY categoria_id HAVING COUNT(categoria_id) >= 3);

# MOSTRAR LOS USUARIOS QUE CREARON UNA ENTRADA UN MARTES 
SELECT * FROM usuarios WHERE id IN (SELECT usuario_id FROM entradas WHERE DAYOFWEEK(fecha) = 3);

# MOSTRAR EL NOMBRE DEL USUARIO QUE TENGA MAS ENTRADAS
SELECT CONCAT(nombre.' '.apellidos) AS 'El usuario con mas entradas' FROM usuarios WHERE id (SELECT usuario_id FROM entradas group by usuario_id order by count(id) desc limit 1);

# MOSTRAR LAS CATEGORIAS SIN ENTRADAS
SELECT * FROM categorias WHERE id not in (SELECT categoria_id FROM entradas);
