# MOSTRAR TODOS LOS REGISTROS / FILAS DE UNA TABLA
SELECT email, nombre, apellidos FROM usuarios;

# MOSTRAR TODOS LOS CAMPOS
SELECT * FROM usuarios;

# OPERADORES ARITMETICOS
SELECT email, (7+7) AS 'operacion' FROM usuarios;

# FUNCIONES MATEMATICAS
SELECT  ABS(7) AS 'operacion' FROM usuarios;

/*
OPERADORES MATEMATICOS

ABS = valor absoluto
CEIL = redondear decimal al alfa
FLOOR = redondear numero al beta

HAY MAS FUNCIONES ARITMETICAS QUE SE PUEDEN SACAR DE INTERNET
*/

# PARA SACER REGISTROS DE TEXTOS EN MAYUSCULAS
SELECT UPPER(nombre) FROM usuarios;

# PARA HACER LO MISMO QUE EL COMANDO ANTERIOR PERO EN MINUSCULAS
SELECT LOWER(nombre) FROM usuarios;

# PARA CONCATENAR CAMPOS
SELECT CONCAT(nobmre.' '.apellidos) FROM usuarios;

#  FUNCIONES PARA TRABAJAR CON FECHAS

# FUNCION PARA MOSTRAR LA FECHA ACTUAL
SELECT email. fecha, CURDATE() FROM usuarios;

# FUNCION PARA COMPRAR LOS DIAS QUE HAY DE DIFERENCIA ENTRE UNA FECHA Y OTRA
SELECT email, DATEDIFF(fecha, CURDATE()) FROM usuarios;

# PARA SACAR EL NOMBRE DEL DIA
SELECT email, DAYNAME(fecha) FROM usuarios;

# PARA SACAR EL NUMERO DEL DIA DEL MES 
SELECT email, DAYOFMONTH(fecha) FROM usuarios;

# PARA SACER EL NUMERO DEL DIA DE LA SEMANA
SELECT email, DAYOFWEEK(fecha, CURDATE()) FROM usuarios;

# PARA SACAR EL NUMERO DEL DIA DEL AÑO
SELECT email, DAYOFYEAR(fecha, CURDATE()) FROM usuarios;

